# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linkedsymbols <- function(initial, final, symbol) {
    .Call('RTrade_linkedsymbols', PACKAGE = 'RTrade', initial, final, symbol)
}

CalculateEquityCurve <- function(symbol, all, trades, size, brokerage) {
    .Call('RTrade_CalculateEquityCurve', PACKAGE = 'RTrade', symbol, all, trades, size, brokerage)
}

GenerateTrades <- function(all) {
    .Call('RTrade_GenerateTrades', PACKAGE = 'RTrade', all)
}

GenerateSignals <- function(all, amount) {
    .Call('RTrade_GenerateSignals', PACKAGE = 'RTrade', all, amount)
}

ExRem <- function(vec1, vec2) {
    .Call('RTrade_ExRem', PACKAGE = 'RTrade', vec1, vec2)
}

Flip <- function(vec1, vec2) {
    .Call('RTrade_Flip', PACKAGE = 'RTrade', vec1, vec2)
}

BarsSince <- function(vec1) {
    .Call('RTrade_BarsSince', PACKAGE = 'RTrade', vec1)
}

Trend <- function(date, high, low, close) {
    .Call('RTrade_Trend', PACKAGE = 'RTrade', date, high, low, close)
}

